// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.controller('DictionaryController', function($scope, $state, $timeout, HttpAuth, Notification, Language, groups) {
  $scope.groups = groups.data;
  $scope.showProperties = true;
  $scope.constant = Language;
  $scope.word = {
    eng: null,
    rus: null,
    group: null
  };
  $scope.group = {
    name: null
  };
  $scope.hideRus = false;
  $scope.hideTrans = false;
  $scope.hideEng = false;
  $scope.hideProperties = function(group) {
    return group.show = !group.show;
  };
  $scope.showAllProperties = function() {
    $scope.showProperties = false;
    return angular.forEach($scope.groups, function(group) {
      return group.show = true;
    });
  };
  $scope.closeAllProperties = function() {
    $scope.showProperties = true;
    return angular.forEach($scope.groups, function(group) {
      return group.show = false;
    });
  };
  $scope.filterChange = function() {
    $scope.showProperties = true;
    return angular.forEach($scope.groups, function(group) {
      return group.show = true;
    });
  };
  $scope.hide = function(property, type) {
    return angular.forEach(property.words, function(word) {
      if (type === 'rus') {
        word.hideRus = true;
      }
      if (type === 'trans') {
        word.hideTrans = true;
      }
      if (type === 'eng') {
        return word.hideEng = true;
      }
    });
  };
  $scope.addGroup = function() {
    return HttpAuth.post('main.php?act=addGroup', {
      group: $scope.group
    }).then(function(response) {
      Notification.show(response);
      return $timeout(location.reload(), 2000);
    }, function(error) {
      return Notification.error(error);
    });
  };
  $scope.addWord = function() {
    return HttpAuth.post('main.php?act=addWord', {
      words: $scope.word
    }).then(function(response) {
      Notification.show(response);
      return $timeout(location.reload(), 3000);
    }, function(error) {
      return Notification.error(error);
    });
  };
  $scope.updateWordModal = function(word) {
    $scope.word = word;
    return angular.forEach($scope.groups, function(group) {
      if (word.group_id === group.id) {
        return word.group = group;
      }
    });
  };
  $scope.trainig = function() {
    return $state.transitionTo('trainig', {
      reload: true
    });
  };
  $scope.removeWord = function() {};
  return $scope.saveWord = function() {};
});

//# sourceMappingURL=DictionaryController.map
