// Generated by CoffeeScript 1.7.1
'use strict';
MainModule.controller('TrainingController', function($scope, Language, $timeout, $state, words, Notification) {
  $scope.words = words.data;
  $scope.constant = Language;
  $scope.languages = [
    {
      id: 1,
      name: $scope.constant.russian.rus,
      value: 'rus'
    }, {
      id: 2,
      name: $scope.constant.english.rus,
      value: 'eng'
    }
  ];
  $scope.training = {
    number: 3,
    language: null
  };
  $scope.hide = function(words, type) {
    return angular.forEach(words, function(word) {
      if (type === 'rus') {
        word.hideRus = true;
      }
      if (type === 'trans') {
        word.hideTrans = true;
      }
      if (type === 'eng') {
        return word.hideEng = true;
      }
    });
  };
  $scope.compareRandom = function(a, b) {
    return Math.random() - 0.5;
  };
  $scope.getTrainingWords = function() {
    $scope.trainWords = [];
    if ($scope.training.language !== null) {
      $scope.trainWords = angular.copy($scope.words);
      $scope.trainWords.sort($scope.compareRandom);
      $scope.trainWords = $scope.trainWords.splice(0, $scope.training.number);
      return $scope.hide($scope.trainWords, $scope.training.language.value);
    } else {
      return Notification.error($scope.constants.noLanguage.rus);
    }
  };
  return $scope.back = function() {
    return window.history.back();
  };
});

//# sourceMappingURL=TrainingController.map
